### PR TITLE
Dac6 1900 fileupload services upgrade bootstrap play to fix security vulnerability

### PR DESCRIPTION
**Pull request by scheung38**

### CODE REVIEW

**Comment by scheung38** [comment]
I guess it was raised before, but didn't see solution?

James Whiteley
Has anyone managed to get scoverage working with Scala 2.12.13 (and Play 2.7)? scoverage version 1.6.1 builds fine but running a coverage report I get the error
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
(along with a lot of other stack trace which doesn’t look relevant)
[Thread in community-scala](https://hmrcdigital.slack.com/archives/C0JR9LZGD/p1615991748000200?thread_ts=1615991748000200&cid=C0JR9LZGD) | [17 Mar 2021](https://hmrcdigital.slack.com/archives/C0JR9LZGD/p1615991748000200?thread_ts=1615991748000200&cid=C0JR9LZGD) | [View message](https://hmrcdigital.slack.com/archives/C0JR9LZGD/p1615991748000200?thread_ts=1615991748000200&cid=C0JR9LZGD)

**Review by ers2015112 — APPROVED** [review]

**Review by ers2015112 — APPROVED** [review]

**Review by ers2015112 — APPROVED** [review]
